# Datasource BaseSetting
my.datasource.abstract:
    driverClassName: com.mysql.jdbc.Driver
    sqlScriptEncoding: UTF-8
    # pooling
    maxActive: 15
    maxIdle: 10
    minIdle: 5
    initialSize: 2
    # Re-connect
    validationQuery: SELECT 1 FROM DUAL
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 600000
    minEvictableIdleTimeMillis: 600000
# datasource1
datasource.data1:
    url: jdbc:mysql://localhost:3306/sample01
    username: user01
    password: pass
# datasource2
datasource.data2:
    url: jdbc:mysql://localhost:3306/sample02
    username: user02
    password: pass
    